spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:9045/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lowerCaseServiceId: true
      routes:
        - id: corporateclient-route
          uri: lb://CORPORATECLIENT  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/clients/**  # Route requests with /accounts/** path to the "accounts" service
          filters:
            - AuthenticationFilter

        - id: usermanagementservice-route
          uri: lb://USERMANAGEMENTSERVICE  # Load balance to the "security" service registered with Eureka
          predicates:
            - Path=/auth/**




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Corporate client loan application Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      gatewayserver:
        com: DEBUG
server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8071/eureka/"