server:
  port: 9044

spring:
  main:
    allow-circular-references: true
  application:
    name: "corporateclient"
  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://localhost:3306/corporateclient?serverTimezone=UTC
    username: root
    password: Mastanbi@12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:9045/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
info:
  app:
    name: "corporateclient"
    description: " corporateclient  Application"
    version: "1.0.0"
logging:
  level:
    com:
      accounts:
        com: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

usermanagementservice:
  service:
    url: http://localhost:9047



